# Generated by Django 3.0.6 on 2020-09-09 16:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='naam')),
                ('description', models.TextField(verbose_name='omschrijving')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='naam')),
                ('start_year', models.IntegerField(verbose_name='jaartal (begin)')),
                ('end_year', models.IntegerField(verbose_name='jaartal (eind)')),
                ('main_contact_email', models.EmailField(max_length=254, verbose_name='e-mailadres voor contact')),
                ('event_day', models.DateField(verbose_name='datum van het evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(verbose_name='korte omschrijving')),
                ('long_description', tinymce.models.HTMLField(verbose_name='lange omschrijving')),
                ('photo', models.FileField(blank=True, null=True, upload_to='speakers/', verbose_name='foto')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='voornaam')),
                ('last_name', models.CharField(max_length=300, verbose_name='achternaam')),
                ('photo', models.FileField(blank=True, null=True, upload_to='commissioners/', verbose_name='foto')),
                ('linkedin_page', models.URLField(max_length=300, verbose_name='linkedin-pagina')),
                ('visible', models.BooleanField(default=True, verbose_name='zichtbaar')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Committee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.CommissionerRole')),
            ],
        )
    ]
