# Generated by Django 3.0.6 on 2020-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_site_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissioner',
            name='committee',
        ),
        migrations.AddField(
            model_name='commissioner',
            name='committee',
            field=models.ManyToManyField(related_name='commissioners', to='core.Committee'),
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='committee',
        ),
        migrations.AddField(
            model_name='speaker',
            name='committee',
            field=models.ManyToManyField(related_name='speakers', to='core.Committee'),
        ),
    ]
