# Generated by Django 3.0.6 on 2020-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200909_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioner',
            name='committee',
            field=models.ManyToManyField(related_name='commissioners', to='core.Committee', verbose_name='commissies'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='committee',
            field=models.ManyToManyField(related_name='speakers', to='core.Committee', verbose_name='commissies'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_kind', models.CharField(choices=[('talk', 'Talk'), ('workshop', 'Workshop'), ('break', 'Break')], max_length=300, verbose_name='soort activiteit')),
                ('name', models.CharField(max_length=300)),
                ('minimum_number_of_people', models.IntegerField(verbose_name='mimum aantal mensen benodigd')),
                ('maximum_number_of_people', models.IntegerField(verbose_name='maximaal aantal mensen toegestaan')),
                ('location', models.CharField(max_length=300)),
                ('commences_at', models.DateTimeField(verbose_name='begint op')),
                ('finishes_at', models.DateField(verbose_name='eindigt op')),
                ('speaker', models.ManyToManyField(related_name='activities', to='core.Speaker', verbose_name='sprekers')),
            ],
        ),
    ]
