# Generated by Django 3.0.6 on 2020-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200909_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(default='Victor', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(default='Paalman', max_length=300),
            preserve_default=False,
        ),
    ]
