# Generated by Django 3.0.6 on 2020-09-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200909_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='naam')),
                ('css_class', models.CharField(max_length=300, verbose_name='css-class')),
                ('order', models.IntegerField(unique=True, verbose_name='volgorde')),
            ],
        ),
        migrations.AlterField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(max_length=300, verbose_name='voornaam'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(max_length=300, verbose_name='achternaam'),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='naam')),
                ('website', models.URLField(verbose_name='website')),
                ('logo', models.FileField(upload_to='sponsors/', verbose_name='logo')),
                ('committee', models.ManyToManyField(related_name='sponsoren', to='core.Committee', verbose_name='commissies')),
                ('sponsorship_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SponsorshipTier', verbose_name='soort sponsorschap')),
            ],
        ),
    ]
