# Generated by Django 3.0.6 on 2020-09-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200909_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='finishes_at',
            field=models.DateTimeField(verbose_name='eindigt op'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='committee',
            field=models.ManyToManyField(related_name='sponsors', to='core.Committee', verbose_name='commissies'),
        ),
    ]
