# Generated by Django 3.0.6 on 2020-09-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200909_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='speaker',
            new_name='speakers',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_organizational',
        ),
    ]
