# Generated by Django 3.0.6 on 2021-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210315_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioner',
            name='official_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
