# Generated by Django 3.0.6 on 2020-09-09 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('hero_text', tinymce.models.HTMLField(default=None, null=True, verbose_name='hero-tekst')),
                ('body', tinymce.models.HTMLField(default=None, null=True, verbose_name='inhoud')),
                ('include_in_menu', models.BooleanField(default=True, verbose_name='laat zien in menu')),
                ('order', models.IntegerField(verbose_name='volgorde')),
                ('is_two_column_page', models.BooleanField(default=False, verbose_name='pagina heeft twee kolommen')),
                ('second_column_body', tinymce.models.HTMLField(default=None, null=True, verbose_name='inhoud van tweede kolom')),
                ('visible', models.BooleanField(default=True, verbose_name='zichtbaar')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='aanmaakdatum')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sites', models.ManyToManyField(related_name='pages', to='core.Site')),
            ],
        ),
    ]
