# Generated by Django 3.0.6 on 2020-09-09 16:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='hero_button_enabled',
            field=models.BooleanField(default=False, verbose_name='schakel knop onder hero-tekst in'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='hero_button_link',
            field=models.URLField(default='', max_length=300, verbose_name='koppeling achter de knop onder de hero-tekst'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticpage',
            name='hero_button_text',
            field=models.CharField(default='', max_length=300, verbose_name='tekst van de knop onder de hero-tekst'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='hero_text',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='hero-tekst'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='second_column_body',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='inhoud van tweede kolom'),
        ),
    ]
