# Generated by Django 3.0.6 on 2020-09-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200909_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='hero_button_enabled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='schakel knop onder hero-tekst in'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='tekst van de knop onder de hero-tekst'),
        ),
    ]
